<?php 

/**
 * GeoStores rules admin template
 *
 * @category   Aydus
 * @package	   Aydus_GeoStores
 * @author     Aydus Consulting <davidt@aydus.com>
 */
?>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="icon-head head-tax-rate-importExport"><?php echo Mage::helper('aydus_geostores')->__('GeoStores Rules') ?></h3></td>
        </tr>
    </table>
</div>
<div class="entry-edit">

    <div class="rules">
    
        <form id="rules_form" action="<?php echo $this->getUrl('*/*/save') ?>" method="post" enctype="application/x-www-form-urlencoded">
			<input type="hidden" id="selectUrl" name="selectUrl" value="<?php echo $this->getUrl('*/*/select') ?>" />
        	<?php echo $this->getBlockHtml('formkey')?>
            
            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('aydus_geostores')->__('Manage Rules') ?></h4>
            </div>
            <fieldset>
            
            	<ul>
            		<li><?php echo Mage::helper('aydus_geostores')->__('Enter your Rules here, one per row.') ?>.</li>
            		<li>
                        Click the add button
                		<img src="<?php echo $this->getSkinUrl('images/rule_component_add.gif')?>" alt="" class="v-middle">
                		to add a new rule and the remove button <img src="<?php echo $this->getSkinUrl('images/rule_component_remove.gif')?>" alt="" class="v-middle">
                		to remove the rule. Drag and drop to reorder.            		
            		</li>            		
            	</ul>
                
                <ul id="rules" class="rules">
                
                <?php if ($this->hasRules()):?>
                    <?php foreach ($this->getRulesCollection() as $rule) : ?>
                	<li class="rule">
                	   <?php echo $this->getChild('geostores_rule')->setRule($rule)->toHtml(); ?>
                    </li>
                    <?php endforeach; ?>
                <?php endif; ?>
                
                	<li class="rule">                	
	 					<span class="rule-add">
	 						<a href="#" class="label">
		 						<img src="<?php echo $this->getSkinUrl('images/rule_component_add.gif')?>" class="v-middle" alt="" title="Add a new Rule" />
	 						</a>
						</span> 
                	</li>
                </ul>
            
            	<ul>
            		<li>
					    <?php if (Mage::getSingleton('admin/session')->isAllowed('system/store')): ?>
					    <p style="margin:10px 0 0;">
					        <a href="<?php echo $this->getUrl('*/system_store') ?>"><?php echo $this->__('Manage Stores') ?></a>
					    </p>
					    <?php endif; ?>            		
            		</li>
            		<li>
		                <?php echo $this->getButtonHtml('Save Rules', "this.form.submit()", null, 'saveRulesButton') ?>
            		</li>
            	</ul>
			                
            </fieldset>
        </form>
    </div>
    
    <?php /* Rules params template */ ?>
	<div id="ruleTemplate" style="display:none">
	
        <?php echo $this->getChild('geostores_rule')->setRule(null)->toHtml(); ?>
	
	</div>    
    <div class="clear"></div>
</div>
<script type="application/javascript">
(function($){

	$(function(){
		
		geoStores.init();
		$( "#rules" ).sortable();
		
	});
	
})(jQuery);

</script>

