<?php

/**
 * GeoStores rule admin template
 *
 * @category   ExtensionsStore
 * @package	   ExtensionsStore_GeoStores
 * @author     Extensions Store <admin@extensions-store.com>
 */
$rule = $this->getRule();
?>
		<span class="rule-params" style="">
		
			<p class="switcher">
			
				<span class="rule-store rule-param">
					<label for="store"><?php echo $this->__('If the user comes to the store') ?></label>
				    <a href="javascript:void(0)" class="label" <?php if(!$this->hasRule()):?>style="display:none"<?php endif ?>><?php echo $rule->getSelectedStoreLabel() ?></a>
					<span class="element" <?php if(!$this->hasRule()):?>style="display:inline-block"<?php endif ?>>
    					<select name="store[]" class="rule-select rule-store-select">
    						<option value="" selected="selected"><?php echo $this->__('-- Select --') ?></option>
    				    	<?php foreach ($this->getStoreOptions() as $option): ?>
    				    	<option value="<?php echo $this->__($option['value']) ?>" <?php if($rule->getStore()==$option['value']):?>selected="selected"<?php endif ?> class="<?php echo $this->__($option['class']) ?>"><?php echo $this->__($option['label']) ?></option>
    				    	<?php endforeach; ?>
    				    </select>	
				    </span>							
				</span>
				
				<span class="rule-op rule-param" <?php if(!$this->hasRule()):?>style="display:none"<?php endif ?>>
					<label for="op"><?php echo $this->__("and the user's location") ?></label>
				    <a href="javascript:void(0)" class="label" <?php if(!$this->hasRule()):?>style="display:none"<?php endif ?>><?php echo $rule->getSelectedOpLabel() ?></a>
				    <span class="element" <?php if(!$this->hasRule()):?>style="display:inline-block"<?php endif ?>>
    					<select name="op[]" class="rule-select rule-op-select">
    						<option value="" selected="selected"><?php echo $this->__('-- Select --') ?></option>
    				    	<?php foreach ($rule->getOpsOptionArray() as $option): ?>
    				    	<option value="<?php echo $this->__($option['value']) ?>" <?php if($rule->getOp()==$option['value']):?>selected="selected"<?php endif ?>><?php echo $this->__($option['label']) ?></option>
    				    	<?php endforeach; ?>			 							
    					</select>
					</span>
				</span>		 							
				
				<span class="rule-country rule-param" <?php if(!$this->hasRule()):?>style="display:none"<?php endif ?>>
					<span class="rule-param-wait"></span>
					<label for="country"><?php echo $this->__('in the country') ?></label>
				    <a href="javascript:void(0)" class="label" <?php if(!$this->hasRule()):?>style="display:none"<?php endif ?>><?php echo $rule->getSelectedCountryLabel() ?></a>
				    <span class="element" <?php if(!$this->hasRule()):?>style="display:inline-block"<?php endif ?>>
    				    <select name="country[]" class="rule-select rule-country-select" <?php if(!$this->hasRule()):?>disabled="disabled"<?php endif ?>>
    					<?php if ($this->hasRule()) : ?>
    					<?php foreach ($this->getCountryOptions($rule->getStore(), false) as $option): ?>
    					   	<option value="<?php echo $this->__($option['value']) ?>" <?php if($rule->getCountry()==$option['value']):?>selected="selected"<?php endif ?>><?php echo $this->__($option['label']) ?></option>
    					<?php endforeach; ?>			 							
    					<?php endif; ?>
    					</select>	
					</span>	 						
				</span>
				
				<span class="rule-region rule-param" <?php if(!$this->hasRule() || !$rule->getCountry()):?>style="display:none"<?php endif ?>>
					<span class="rule-param-wait"></span>
					<label for="region"><?php echo $this->__('and the regions') ?></label>
				    <a href="javascript:void(0)" class="label" <?php if(!$this->hasRule()):?>style="display:none"<?php endif ?>><?php echo $rule->getSelectedRegionLabel() ?></a>
					<span class="element" <?php if(!$this->hasRule()):?>style="display:inline-block"<?php endif ?>>
    					<select name="region[]" region_id="<?php echo $rule->getRegionId() ?>" class="rule-select rule-region-select" <?php if(!$this->hasRule()):?>disabled="disabled"<?php endif ?>>
    					<?php if ($this->hasRule()) : ?>
    					<?php foreach ($this->getRegionOptions($rule->getStore(), false, $rule->getCountry()) as $option): ?>
    					   	<option value="<?php echo $this->__($option['value']) ?>" <?php if($rule->getRegionId()==$option['value']):?>selected="selected"<?php endif ?>><?php echo $this->__($option['label']) ?></option>
    					<?php endforeach; ?>			 							
    					<?php endif; ?>
    					</select>		
    					<?php /*?>
    					<input type="text" name="region[]" style="display:none" title="Add regions, separated by commas" val="" <?php if(!$this->hasRule()):?>disabled="disabled"<?php endif ?> />
    					<?php */ ?>
					</span> 						
				</span>		 						
				
				<span class="rule-city rule-param" <?php if(!$this->hasRule() || !$rule->getRegion()):?>style="display:none"<?php endif ?>>
					<label for="city"><?php echo $this->__('and the cities') ?></label>
				    <a href="javascript:void(0)" class="label" <?php if(!$this->hasRule()):?>style="display:none"<?php endif ?>><?php echo $rule->getSelectedCityLabel() ?></a>
					<span class="element" <?php if(!$this->hasRule()):?>style="display:inline-block"<?php endif ?>>
    				    <input type="text" name="city[]" <?php if(!$this->hasRule()):?>disabled="disabled"<?php endif ?> title="Add cities, separated by commas" />
				    </span>
				</span>		
				
				<span class="rule-redirect rule-param" <?php if(!$this->hasRule()):?>style="display:none"<?php endif ?>>
					<label for="redirect"><?php echo $this->__('then redirect the user to the') ?></label>
				    <a href="javascript:void(0)" class="label" <?php if(!$this->hasRule()):?>style="display:none"<?php endif ?>><?php echo $rule->getSelectedStoreLabel('redirect') ?></a>
					<span class="element" <?php if(!$this->hasRule()):?>style="display:inline-block"<?php endif ?>>
    					<select name="redirect[]" class="rule-select rule-redirect-select">
    						<option value="" selected="selected"><?php echo $this->__('-- Select --') ?></option>
    				    	<?php foreach ($this->getStoreOptions() as $option): ?>
    				    	<option value="<?php echo $this->__($option['value']) ?>" <?php if($rule->getRedirect()==$option['value']):?>selected="selected"<?php endif ?> class="<?php echo $this->__($option['class']) ?>"><?php echo $this->__($option['label']) ?></option>
    				    	<?php endforeach; ?>
    				    </select>					
				    </span>			
				</span>		 
				
				<span class="rule-remove">
					<a href="#" title="Remove">
						<img src="<?php echo $this->getSkinUrl('images/rule_component_remove.gif')?>" alt="" class="v-middle">
					</a>
				</span>									
				
			</p>
			
		</span>    	